#!/usr/bin/env bash

# STEP 1: Determinate the required values

PACKAGE="main"
VERSION="$(git describe --tags --always --abbrev=0)"
COMMIT_HASH="$(git rev-parse --short HEAD)"
BUILD_TIMESTAMP=$(date '+%Y-%m-%dT%H:%M:%S')

# STEP 2: Build the ldflags

LDFLAGS=(
  "-X '${PACKAGE}.Version=${VERSION}'"
  "-X '${PACKAGE}.Commit=${COMMIT_HASH}'"
  "-X '${PACKAGE}.BuildTime=${BUILD_TIMESTAMP}'"
)

# STEP 3: Actual Go build process

go build -v -ldflags="${LDFLAGS[*]}"